### ISSUE TITLE
Markercluster icons served via http on a https site

### ISSUE THREAD

**Issue by davecotter** [JeroenDeDauw/Maps#90] opened 2015-07-23 00:52 UTC
i see that in version 3.2.3 you say fixed a bug stating "Protocol relative URLs are now used, avoiding HTTPS related problems"

however i still see problems with this.
please see my map:
https://karaoke.kjams.com/wiki/Map_Interactive

note the URL icon shows a caution sign instead of the green lock.

**Comment by kghbln** [comment] 2015-07-23 17:39
Affirmative the icons of the markerclusters are still served via http.

http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m1.png to m4.png

**Comment by JeroenDeDauw** [comment] 2015-07-24 20:24
Thanks for reporting @davecotter!

**Comment by davecotter** [comment] 2015-07-24 20:29
happy to help!  :D

**Comment by JeroenDeDauw** [comment] 2016-04-02 21:37
Is this still an issue in Maps 3.5.x?

**Comment by PeterTheOne** [comment] 2016-05-24 21:51
Duplicate of https://github.com/SemanticMediaWiki/SemanticMaps/issues/34, should be fixed with #142. Can someone check?

**Comment by kghbln** [comment] 2016-05-24 22:11
@PeterTheOne Good find! Do to the new PHP requirement I currently cannot directly test (sandbox.smw.o should really go https soonish). However this should indeed be fixed. This one can still be reopened in worst-case.

**Closed by kghbln** 2016-05-24 22:11 UTC
Labels: bug
