### ISSUE TITLE
Using custom images instead of maps

### ISSUE THREAD

**Issue by krabina** [JeroenDeDauw/Maps#335] opened 2017-06-01 11:45 UTC
Using OpenLayers there should be a possibility to use markers over a custom image instead of a map. I think that this features has been avialable in maps at some time, but I couldn't find any information.

Is this still possible? If not, it might be interesting to add it (again)...

**Comment by JeroenDeDauw** [comment] 2017-06-01 11:56
Duplicate of https://github.com/JeroenDeDauw/Maps/issues/311

**Closed** 2017-06-01 11:56 UTC
Labels: duplicate, layers, OpenLayers
