### ISSUE TITLE
global configuration variables overwritten

### ISSUE THREAD

**Issue by cyungmann** [JeroenDeDauw/Maps#471] opened 2018-09-05 04:20 UTC
### Setup

- Maps version: 6.0
- MW version: 1.31.0
- PHP version: 7.1.8 (fpm-fcgi)
- SMW version (if applicable): 2.5.7

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

When I have the following excerpt in LocalSettings.php:

```
wfLoadExtension( 'Maps' );
$GLOBALS['egMapsDefaultService'] = 'googlemaps3';
$GLOBALS['egMapsGMaps3ApiKey'] = 'REDACTED';
$GLOBALS['egMapsDefaultGeoService'] = 'google';
```

it seems that all the global configuration variables get overridden, as the extension still defaults to leaflet and if I explicitly specify to use google maps using the tag syntax, I get an error about missing the google maps API key.

**However**, if I do the following then everything seems to work correctly:

```
ExtensionRegistry::getInstance()->load("$wgExtensionDirectory/Maps/extension.json");
$GLOBALS['egMapsDefaultService'] = 'googlemaps3';
$GLOBALS['egMapsGMaps3ApiKey'] = 'REDACTED';
$GLOBALS['egMapsDefaultGeoService'] = 'google';
```

I wonder if there is some issue due to the asynchronous nature of wfLoadExtension? I'd be surprised if I'm the first to run into this issue, so maybe it's just user error on my part?

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by JeroenDeDauw** [comment] 2018-09-05 04:40
Confirmed

**Comment by JeroenDeDauw** [comment] 2018-09-05 04:48
The issue is that the whole existing registry stuff happens only after the code in LocalSettings.php was included, and it is during the extension registration that Maps loads the settings.

**Comment by JeroenDeDauw** [comment] 2018-09-05 05:04
Fixed by https://github.com/JeroenDeDauw/Maps/pull/472

Though you will also need to modify LocalSettings, as per https://www.semantic-mediawiki.org/wiki/Maps/Configuration

**Closed as completed** 2018-09-05 05:18 UTC
