### ISSUE TITLE
Semantic Maps initialization class gets loaded twice

### ISSUE THREAD

**Issue by ImBoPhil** [JeroenDeDauw/Maps#286] opened 2016-11-29 16:48 UTC
Maps tries to load the Semantic version of the extension by default and then clashes with itself. This is preventing https://github.com/miraheze from upgrading to MediaWiki 1.28

**Comment by kghbln** [comment] 2016-11-29 20:40
I am not absolutely sure what you are trying to convey. You are installing Maps and at the same time it activates the semantic functionality? If you would like to disable this you could use `$egMapsDisableSmwIntegration = true;` Also note that if you upgrade to Maps 4.0 or higher you will have to uninstall Semantic Maps 3.4.2 or lower.

**Comment by kghbln** [comment] 2016-12-01 15:05
@ImBoPhil Any follow-up on this. Does it work for Miraheze now?

**Comment by LegoFan4000** [comment] 2016-12-02 12:18
We have not done it yet

**Comment by kghbln** [comment] 2016-12-02 12:34
It sounded like an urgent issue. Take your time then.

**Comment by Reception123** [comment] 2016-12-02 18:40
@kghbln It is an urgent issue as we want to get 1.28 ASAP. $egMapsDisableSmwIntegration = true; didn't work. We are still getting PHP Fatal error:  Cannot redeclare class SemanticMaps in /srv/mediawiki/w/extensions/Maps/Maps.php on line 259" error

**Comment by JeroenDeDauw** [comment] 2016-12-02 23:59
This suggests you have the Semantic Maps functionality twice. Try doing a string search on `class SemanticMaps` in your whole MW install. Only one result should come up.

**Comment by Reception123** [comment] 2016-12-03 15:26
@JeroenDeDauw Got this using grep -rl "class SemanticMaps":
grep: w/maintenance/.mweval_history: Permission denied
w/extensions/Maps/Maps.php
w/extensions/Maps/SemanticMaps/SemanticMaps.hooks.php

**Comment by JeroenDeDauw** [comment] 2016-12-04 01:52
That looks fine (the last match is something else)... Not sure what is going wrong then, though I have an idea of making a change to the code that will probably solve the issue for you.

**Comment by LegoFan4000** [comment] 2016-12-04 02:12
Ok, what is your idea.

**Comment by JeroenDeDauw** [comment] 2016-12-04 02:13
Get rid of the SemanticMaps class from the entry point, either by moving it into a dedicated file or by changing it to not be a class.

I'll poke at this later and make a new patch release

**Comment by JeroenDeDauw** [comment] 2016-12-04 09:50
I'm going to close this under the assumption that the issue is fixed in the `4.0.2` release. If that is not the case, please reopen.

**Closed by JeroenDeDauw** 2016-12-04 09:50 UTC
Labels: bug

**Comment by JohnFLewis** [comment] 2016-12-04 14:18
That assumption was correct. Thanks.
