### ISSUE TITLE
Maps and MobileFrontend

### ISSUE THREAD

**Issue by k41s** [JeroenDeDauw/Maps#12] opened 2014-03-22 09:27 UTC
Maps doesn't work with MobileFrontend. Endless "Loading map...". MediaWiki 1.22.2, Maps 3.0, and MobileFrontend.
http://www.mediawiki.org/wiki/Extension_talk:MobileFrontend#Maps_and_MobileFrontend_38039
@jdlrobson

**Comment by jehovahsays** [comment] 2015-01-21 11:33
Which skin template are you using?

**Comment by lfschenone** [comment] 2015-01-21 14:00
Minerva skin on mobile, customised Vector on desktop.

**Comment by jehovahsays** [comment] 2015-01-21 15:25
send us the link to maps extension you have installed on your mediawiki website.

**Comment by lfschenone** [comment] 2015-01-21 15:30
https://github.com/JeroenDeDauw/Maps

**Comment by jehovahsays** [comment] 2015-01-21 15:35
is this google maps?

**Comment by lfschenone** [comment] 2015-01-21 15:36
Yes. Your three questions so far you could have found out for yourself very easily.

**Comment by jehovahsays** [comment] 2015-01-21 15:37
We are going to install this on our mediawiki to recreate the same error to fix that error.

**Comment by jehovahsays** [comment] 2015-01-21 15:38
ok we forked the repo. give a second to recreate the errors.

**Comment by jehovahsays** [comment] 2015-01-21 15:47
first error is blank page. what versions of mediawiki is maps compatible with.

**Comment by jehovahsays** [comment] 2015-01-21 15:55
we needed to download extension installer. hold on. we thought we already had that installed. be right back.

**Comment by jehovahsays** [comment] 2015-01-21 16:02
installing maps

**Comment by jehovahsays** [comment] 2015-01-21 16:05
maps install via composer

**Comment by lfschenone** [comment] 2015-01-21 16:09
THIS IS NOT A CHAT
Keep your useless comments to yourself. Only post here information that may be useful to solving the issue!

**Comment by jehovahsays** [comment] 2015-01-21 16:12
Here are the error that need to be corrected in you code.
[723b2fad] /core/mw-config/?page=ExistingWiki MWException from line 337 of C:\inetpub\wwwroot\CORE\includes\MagicWord.php: Error: invalid magic word 'coordinates'

Backtrace:

#0 C:\inetpub\wwwroot\CORE\includes\MagicWord.php(262): MagicWord->load(string)
#1 C:\inetpub\wwwroot\CORE\includes\parser\Parser.php(5182): MagicWord::get(string)
#2 C:\inetpub\wwwroot\CORE\extensions\Maps\extensions\Validator\src\legacy\ParserHook.php(210): Parser->setFunctionHook(string, array, integer)
#3 C:\inetpub\wwwroot\CORE\extensions\Maps\Maps.php(97): ParserHook->init(Parser)
#4 [internal function]: Installer::{closure}(Parser)
#5 C:\inetpub\wwwroot\CORE\includes\Hooks.php(209): call_user_func_array(Closure, array)
#6 C:\inetpub\wwwroot\CORE\includes\parser\Parser.php(306): Hooks::run(string, array)
#7 C:\inetpub\wwwroot\CORE\includes\parser\Parser.php(316): Parser->firstCallInit()
#8 C:\inetpub\wwwroot\CORE\includes\parser\Parser.php(5025): Parser->clearState()
#9 C:\inetpub\wwwroot\CORE\includes\parser\Parser.php(402): Parser->startParse(Title, ParserOptions, integer, boolean)
#10 C:\inetpub\wwwroot\CORE\includes\installer\Installer.php(631): Parser->parse(string, Title, ParserOptions, boolean)
#11 C:\inetpub\wwwroot\CORE\includes\installer\WebInstaller.php(676): Installer->parse(string, boolean)
#12 C:\inetpub\wwwroot\CORE\includes\installer\WebInstallerPage.php(392): WebInstaller->getInfoBox(string)
#13 C:\inetpub\wwwroot\CORE\includes\installer\WebInstallerPage.php(380): WebInstallerExistingWiki->showKeyForm()
#14 C:\inetpub\wwwroot\CORE\includes\installer\WebInstaller.php(280): WebInstallerExistingWiki->execute()
#15 C:\inetpub\wwwroot\CORE\mw-config\index.php(79): WebInstaller->execute(array)
#16 C:\inetpub\wwwroot\CORE\mw-config\index.php(38): wfInstallerMain()
#17 {main}

**Comment by jehovahsays** [comment] 2015-01-21 16:19
Usage. Visit our website where we install maps https://www.jehovahsays.net/core/index.php?title=Special:Version

**Comment by jehovahsays** [comment] 2015-01-21 16:22
Review your extension. It works on our website. please visit https://www.jehovahsays.net/core/index.php?title=Main_Page

**Comment by lfschenone** [comment] 2015-01-21 16:25
This issue is about the extension not working on mobile devices. Do your maps work on your mobile devices or not? I just visited your wiki from my mobile device and it doesn't work for me. Not surprised.

**Comment by jehovahsays** [comment] 2015-01-21 16:32
No. map unsuccessful. stuck at loading map...
please visit our website to see your results.
https://www.jehovahsays.net/core/index.php?title=Main_Page&mobileaction=toggle_view_mobile
here is the code we found in the source code.

<div id="map_google3_1" style="width: auto; height: 350px; background-color: #cccccc; overflow: hidden;" class="maps-map maps-googlemaps3">Loading map...<div style="display:none" class="mapdata">{"minzoom":false,"mappingservice":"googlemaps3","type":"ROADMAP","geoservice":"geonames","types":["ROADMAP","SATELLITE","HYBRID","TERRAIN"],"maxzoom":false,"width":"auto","height":"350px","centre":{"text":"","title":"","link":"","lat":40.7127837,"lon":-74.0059413,"alt":0,"address":"","icon":"","group":"","inlineLabel":"","visitedicon":""},"title":"","label":"","icon":"","visitedicon":"","lines":[],"polygons":[],"circles":[],"rectangles":[],"wmsoverlay":false,"copycoords":false,"static":false,"zoom":14,"layers":[],"controls":["pan","zoom","type","scale","streetview"],"zoomstyle":"DEFAULT","typestyle":"DEFAULT","autoinfowindows":false,"resizable":false,"kmlrezoom":false,"poi":true,"markercluster":false,"tilt":0,"imageoverlays":[],"kml":[],"gkml":[],"fusiontables":[],"searchmarkers":"","enablefullscreen":false,"locations":[]}</div></div>

**Comment by jehovahsays** [comment] 2015-01-21 16:34
also a link displays at the bottom of the page in desktop view
Category: Pages with a map rendered by the Maps extension
this page does not exist. maybe it should?

**Comment by jehovahsays** [comment] 2015-01-21 16:37
be right back we might be able to fix this.

**Comment by lfschenone** [comment] 2015-01-21 16:40
The "Category:Pages with a map rendered by the Maps extension" has nothing to do with this issue. Pages with maps are automatically added to that category, you may create it by following the red link or not, as you prefer.

Please go ahead and try to fix this issue, but please don't bomb us with your messages, as we get one email for each message you write. Please be considerate and only post when you fix the issue or need our help to do so.

**Comment by jehovahsays** [comment] 2015-01-21 16:59
Maps_Setting.php
line 275 
broken link 
http://t1.hypercube.telascience.org/cgi-bin/landsat7

**Comment by jehovahsays** [comment] 2015-01-21 17:00
another broken 
line 292
link http://api.maps.yahoo.com/ajaxymap?v=3.0&appid=euzuro-openlayers

**Comment by jehovahsays** [comment] 2015-01-21 17:02
another broken link 
line 294
http://clients.multimap.com/API/maps/1.1/metacarta_04

**Comment by jehovahsays** [comment] 2015-01-21 17:26
This will solve your problem also. 
https://developers.google.com/maps/faq#mapsformobile

**Comment by lfschenone** [comment] 2015-01-21 17:28
Have you been able to solve the issue? If so, would you mind posting instructions, rather than a link to general documentation?

**Comment by JeroenDeDauw** [comment] 2015-01-21 17:41
A pull request with the fix is also very welcome

**Comment by jehovahsays** [comment] 2015-01-21 17:45
There will be much Much work to do but yes.
Give us about 30 mins. to an hour we will then begin to post instructions.
the time here is 12:44PM eastern time in america.
we just need to prepare for files and folders.

**Comment by jehovahsays** [comment] 2015-01-21 18:21
go into folder \extensions\MobileFrontend

**Comment by jehovahsays** [comment] 2015-01-21 18:22
go into folder \extensions\MobileFrontend\includes\skins

**Comment by jehovahsays** [comment] 2015-01-21 18:28
In this folder contains files with the markup you will need to repair your mediawiki extension.
Desktop view and Mobile are two different main pages.
for example, the white space below the mobile menu where you see the main page in mobile view is actually in an iframe.

**Comment by jehovahsays** [comment] 2015-01-21 18:29
Your extension only controls the desktop view main page but not the mobile view main page

**Comment by jehovahsays** [comment] 2015-01-21 18:31
to do this you will need to adopt the php markup located in the template and skin files locate in the folder - \extensions\MobileFrontend\includes\skins

**Comment by jehovahsays** [comment] 2015-01-21 18:33
also you will have to fork some of the the source code located in the main page by right clicking on the home page and viewing the source code.

**Comment by jehovahsays** [comment] 2015-01-21 18:33
Are you still with me?

**Comment by jehovahsays** [comment] 2015-01-22 01:54
You need to get api key for google maps. if you don't have one maps won't work. /play dangerzone

**Comment by kvolden** [comment] 2015-03-23 16:26
I don't know how or why api keys for google maps or main page markup would be relevant to this problem. The issue is that in MobileFrontend's mobile view, maps will not load. In desktop view – with or without the MobileFrontend extension installed and enabled – the maps load. Whether you're actually on a mobile device or on a desktop computer doesn't affect this.

**Comment by dmaglio** [comment] 2015-10-28 15:26
it works: line 138 in includes/resourceloader/ResourceLoaderFileModule.php add 'mobile' in variable $target

**Comment by PeterTheOne** [comment] 2016-08-09 09:31
I guess this isn't a problem anymore, so let's close this.

(Also there is a google api key now.)

**Closed** 2016-08-16 11:02 UTC
Labels: bug
