### ISSUE TITLE
Make sure when building a `SMWDIGeoCoord object` that it uses ISO norm data

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#423] opened 2018-05-12 09:53 UTC
### Setup
- MediaWiki | 1.30.0 (09ff9cf)13:46, 10 May 2018
- PHP | 7.0.27-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.0.0-alpha (497c969) 20:17, 29 April 2018
- Maps | 5.4.0 alpha (5c00ad8) 08:05, 7 May 2018

### Issue
In case the locale does not enforce ISO norm data a fatal error is shown since `SMWDIGeoCoord` unserializes localized Lat/Long (format : 0,xxx, 0,xxxx)

Refs: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3153

### Mitigation
Make sure when building a `SMWDIGeoCoord` object [0] that it uses ISO norm data (i.e. `.` formatted values) instead of a `setlocale` dependant string parsing?

[0] https://github.com/JeroenDeDauw/Maps/blob/master/src/Semantic/DataValues/CoordinateValue.php#L99-L113

**Comment by JeroenDeDauw** [comment] 2018-05-13 03:49
@mwjames how exactly do you figure this is a Maps issue? I don't see anything locale specific or wrong about the linked https://github.com/JeroenDeDauw/Maps/blob/master/src/Semantic/DataValues/CoordinateValue.php#L99-L113

**Comment by JeroenDeDauw** [comment] 2018-05-13 03:54
I'm really confused. If the error is happening in SMWDIGeoCoord, how can it be the fault of the code constructing it? Only by passing in invalid values no? But the SMWDIGeoCoord constructor casts everything it gets to float, so how can a comma vs point issue in Maps cause an error in SMWDIGeoCoord later on? If it got wrongly formatted values I'd expect an immediate error or data corruption, but not a formatting error later on.

**Comment by mwjames** [comment] 2018-05-13 03:56
> @mwjames how exactly do you figure this is a Maps issue?

`SMWDIGeoCoord` contains non ISO data in case of the said setlocale issue and since `SMWDIGeoCoord` is immutable and only created as part of a DataValue,I'm guessing somewhere during the DV/DI composition (most likely during the string parsing) happens the issue.

**Comment by JeroenDeDauw** [comment] 2018-05-13 03:58
> SMW\Exception\DataItemException from line 119 of /var/www/wiki.remixthecommons.org/public_html/core/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_GeoCoord.php: Unserialization of coordinates failed

That is in the DataItem...

**Comment by mwjames** [comment] 2018-05-13 03:59
As outlined in SemanticMediaWiki/SemanticMediaWiki#3153 the issue is that MW sets `setlocale( LC_ALL, $wgShellLocale )` and a `$wgShellLocale = "fr_CA.utf8";` references which caused the mismatch between `,` and `.` due to FR using `,` as `.`.

**Comment by mwjames** [comment] 2018-05-13 04:00
> SMW\Exception\DataItemException from line 119 of /var/www/wiki.remixthecommons.org/public_html/core/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_GeoCoord.php: Unserialization of coordinates failed

That only happens afterwards when it tries to read the data from the DB which contained `,` lat, log values (== non ISO).

**Comment by JeroenDeDauw** [comment] 2018-05-13 04:01
And how did the data get there? I would assume that `doUnserialize` (where the error happens) works with data that came from `getSerialization`, which uses two floats and is under control of the DataItem... What does this have to do with Maps?

**Comment by mwjames** [comment] 2018-05-13 04:02
When the Geo DV parses a string just make sure that Maps creates a DI with ISO data that's all.

**Comment by JeroenDeDauw** [comment] 2018-05-13 04:03
How can it not be ISO? The constructor casts to float.

**Comment by mwjames** [comment] 2018-05-13 04:06
Look, if you think that Maps is doing everything correctly and you are sure that nothing gets in the way during the parsing because you have tested it then this is fine and you can close the issue.

**Comment by JeroenDeDauw** [comment] 2018-05-13 04:09
I checked if the implode doing an implicit cast from float to string is impacted by the locale and it looks not https://3v4l.org/2sBXg

Not sure Maps is doing the right thing. Perhaps the parser it uses has an issue, though I still do not see how that could lead to the deserialization error. So unless there is info on how to reproduce this I will indeed close it.

**Comment by mwjames** [comment] 2018-05-13 04:12
> that could lead to the deserialization error. So unless there is info on how to reproduce this I will indeed close it.

Use MW 1.29 or 1.30 (due to changes in MW how `setlocale` is used ), set `$wgShellLocale = "fr_CA.utf8";` save a wiki page with geo data and you will have non ISO data in the DB which when retrieving those data will create the exception.

**Comment by JeroenDeDauw** [comment] 2018-05-13 04:32
Both the storage of the data and the retrieval is done by SMW no?

To follow those instructions I need a working MW install and whatnot. Setting that up takes too much time, so please provide something a bit more narrowed down (definitely not including more than Maps itself)

**Closed** 2018-05-13 04:42 UTC
Labels: bug

**Comment by kghbln** [comment] 2018-05-13 08:00
Well if people stick to the locale recommended by MW we will not have issues here. An update of the README was merged to make this recommendation more clear. In the end this was probably broken wherever during the last ten years and we only got our first report a fortnight ago ... Still it would be nice to have some code preventing this in the first place but ... ;)
