### ISSUE TITLE
Maps in Dark

### ISSUE THREAD

**Issue by Momo50WM** [JeroenDeDauw/Maps#594] opened 2019-12-25 14:09 UTC
### Setup

- Maps version: 7.15.1
- MW version: 1.34.0
- PHP version: 7.2.17-1+0
- SMW version (if applicable): NO

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

Hi Jeroen ! Maps since last update are in Dark. What is the problem and how to repair it ? 
Thanks !
Cheers
Christian 

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):
See my UserPage on Wikimanche
https://www.wikimanche.fr/Utilisateur:Momo50/Extension_Maps

**Comment by JeroenDeDauw** [comment] 2019-12-25 14:56
Thanks for reporting this. I'm closing the ticket here as it is a duplicate of https://github.com/JeroenDeDauw/Maps/issues/588

**Closed by JeroenDeDauw** 2019-12-25 14:56 UTC
