### ISSUE TITLE
Maps cannot display > 7 location markers

### ISSUE THREAD

**Issue by msamiec** [JeroenDeDauw/Maps#136] opened 2016-04-26 22:00 UTC
Hello,

I didn't find anything in the documentation regarding a maximum # of points on a map so I presume it is a bug. 

Whenever I create a map with > 7 points (both openlayers and googlemaps), the map does not generate any of the points and instead zooms into an area of the ocean. I have been able to test this numerous times by adding/removing single points above the 7 point threshold and it happens without fail. Simply put, I cannot create a map of a Province with 14 markers.

I am using the Maps 3.5 and MediaWiki 1.26.2. Also using PHP 5.4.16 and MariaDB 5.5.44. Unfortunately the wiki is on an intranet and I cannot provide access.

Has anyone seen this issue before?

**Comment by JeroenDeDauw** [comment] 2016-04-27 14:31
Not seen this before. Can you replicate this on a public wiki, such as http://sandbox.semantic-mediawiki.org ?

**Comment by msamiec** [comment] 2016-04-27 19:15
Hello. I now have an account for the Sandbox but don't have the ability to edit. Would screenshots also help show the issue I'm seeing internally?

I noticed an error with Inspector that says no API Key was found.

util.js:220 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
util.js:220 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

**Comment by kghbln** [comment] 2016-04-27 19:19
> Hello. I now have an account for the Sandbox but don't have the ability to edit.

I just confirmed your account. So you still cannot edit?

This API key thing is perhaps an issue but seems unrelated to what you initially reported since "openlayers" did not work either.

**Comment by msamiec** [comment] 2016-04-27 19:44
I'm logged in but still cannot edit. It only gives me the ability to view source code.

I just verified these issues with our web developer and we confirmed that there are no syntax errors in the code. Here's an image of the issue that I uploaded: [http://imgur.com/G7oKnrM](url)

As you can see, sometimes when the code is saved it zooms into the ocean (bottom left). Once I zoom out, it shows a spot around Africa (bottom right). Sometimes when I save it shows all points (top right). Today is the first time I have been able to see > 7 points. Once I add, change text, or simply save again with existing text I may see the blue ocean again.

I've tried to add/remove, line by line, to see if any one line of code offends and causes this issue but there is nothing. The behaviour is erratic.

**Comment by kghbln** [comment] 2016-04-27 19:56
> I'm logged in but still cannot edit. It only gives me the ability to view source code.

I am unable to replicate the issue. I just created a test account myself and everything is working as expected. Just make sure that you are not trying to edit an existing page which happens to be edit protected.

**Comment by msamiec** [comment] 2016-04-27 20:03
Ok, I was able to create a page and replicate the issue: [http://sandbox.semantic-mediawiki.org/wiki/Test_Page](url)

On first edit (see revision history), everything was fine. Once I added new cities and text, I got the blue water issue. Here are the two screenshots: [http://imgur.com/ngspxDN](url)

**Comment by kghbln** [comment] 2016-04-27 20:28
Well we indeed have an issue and it is erratic. Just hit "purge" and sometime one gets the expected results and sometimes the map goes blue. So some sort of caching worry may be involved too. This seems independent from the number of points ([tested up to 12 myself](http://sandbox.semantic-mediawiki.org/wiki/Issue/136_%28M%29)). on - off - off - on = grump ;)

**Comment by JeroenDeDauw** [comment] 2016-04-28 16:00
I'm going to venture a guess that what is happening is that the geocoding service is failing some of the time. One fix is putting in the actual coordinates, which you can obtain for instance via the `#geocode` parser function. It's of course still an issue to be addressed in the extension, at the very least it should inform you of what is going wrong, so you don't need to go on a chase and become a grump bunny.

**Comment by kghbln** [comment] 2016-04-28 16:43
@msamiec Could you test if this is a working solution. Very much appears to be. I guess I should also put a respective note on the docu. So no immediate grump. :)

**Comment by msamiec** [comment] 2016-04-28 17:01
I'm getting similar, erratic behaviour trying to change cities into geocodes.

`{{#geocode:Vancouver, British Columbia}}
{{#geocode:Victoria, British Columbia}}
{{#geocode:Whistler, British Columbia}}
{{#geocode:Tofino, British Columbia}}`

Results in:

49° 16' 57.82" N, 123° 7' 14.66" W
Fatal error: Failed to parse or geocode
Fatal error: Failed to parse or geocode
49° 9' 10.74" N, 125° 54' 23.83" W

However, sometimes it does not fail.

**Comment by msamiec** [comment] 2016-04-29 16:37
Good news... I've managed to convert all cities to geocodes and everything seems to be working fine now. Just a few extra steps needed. Thank you!

**Comment by JeroenDeDauw** [comment] 2016-04-29 17:31
Yeah, that's to be expected. If the geocoding is flaky like I thought, then it will also show up for the `#geocode` parser function.

**Closed** 2016-10-07 01:08 UTC
Labels: bug
