### ISSUE TITLE
Geocoding does not work anymore

### ISSUE THREAD

**Issue by Rudloff** [JeroenDeDauw/Maps#281] opened 2016-11-16 10:36 UTC
### Setup

- MW version: 1.26.4
- DB (MySQL etc.): MySQL 5.6.30
- PHP version: 5.6.27
- Maps version: 4.0.0
- SMW version (if applicable): 2.3.1

### Issue

Geocoding works fine with Maps 3.7.0, but if I update to 3.8 or 4.0, geocoding fails with this error:
```
Fatal error: Failed to parse or geocode
```
Even with a basic request like this: ```{{#geocode:22 rue de Bâle, Strasbourg, France}}```

I can't reproduce on the sandbox so I guess this has something to do with my MediaWiki version.

Here is the full debug log: https://gist.github.com/Rudloff/b45256749b038b4fc813e5ad7eb83fd9

**Comment by JeroenDeDauw** [comment] 2016-11-16 12:17
I can't reproduce this on my box either. The wikitext you posted gives me `48° 34' 24.26" N, 7° 45' 7.60" E`

Which geocording service are you using?

This might be related to https://github.com/JeroenDeDauw/Maps/issues/223

**Comment by Rudloff** [comment] 2016-11-16 12:19
I tried different services and they all fail.

**Comment by JeroenDeDauw** [comment] 2016-11-16 12:34
Do they fail for all values? For instance, does `New York` work? (That one has no special characters)

Note that these geocoding services require your MediaWiki installation making a request to some webservice. So if your server firewall prohibits that, they will fail. Perhaps this should be mentioned in the docs somewhere...

**Comment by Rudloff** [comment] 2016-11-16 12:37
`New York` does not work either (same error).
I don't think this is a firewall issue as it works perfectly with Maps 3.7.

**Comment by JeroenDeDauw** [comment] 2016-11-16 12:45
Oh right... yeah... bit sleepy here :)

**Comment by Rudloff** [comment] 2016-11-16 13:12
I did some tests and there are two separate issues here:
* It always uses the Google service even if I specify another one.
* The Google service fails with this error: `Browser API keys cannot have referer restrictions when used with this API.`

I fixed the second issue by editing my API key (not sure why it works with 3.7 though) but it still does not want to use anything else than Google.
(Geocoders::attemptToGeocode is apparently called withouth the second parameter.)

**Comment by JeroenDeDauw** [comment] 2016-11-16 14:26
Thanks for the debugging. It seems like LocationParser indeed does not pass this parameter. However, that appears to have been the case for quite some time, and is not obviously wrong (this code is a bit confusing...)

**Comment by JeroenDeDauw** [comment] 2016-11-16 14:59
The service parameter being ignored should be fixed by https://github.com/JeroenDeDauw/Maps/pull/283

**Comment by kghbln** [comment] 2016-11-16 16:05
With the same setup apart from MW being 1.27.1 I cannot reproduce either. However, good that the issue was detected and fixed.

**Comment by JeroenDeDauw** [comment] 2016-11-16 16:33
That timing though... just after 4.0 release... I have not even announced it on the list :)

**Closed** 2016-11-18 17:54 UTC
Labels: bug
