### ISSUE TITLE
Add support for rendering with MobileFrontend / Minerva Neue

### ISSUE THREAD

**Issue by kghbln** [JeroenDeDauw/Maps#598] opened 2020-01-03 10:51 UTC
### Setup

- Maps version: 7.15.4 (e0028da) 14:52, 2 January 2020
- MW version: MediaWiki | 1.34.0 (ae6e0c0)15:53, 27 December 2019
- PHP version: 7.2.24-0ubuntu0.18.04.1 (apache2handler)

### Issue

Maps do not render when using the mobile view as provided by MobileFrontend / Minerva Neue. Both GoogleMaps and Leaflet are affected.

Originally reported on [mediawiki.org](https://www.mediawiki.org/wiki/Topic:Ve0pru8m3ygl58vt). Suggestion on how to resolve [provided here.](https://www.mediawiki.org/w/index.php?title=Topic:Vdy3pu34oy1n4l55&topic_showPostId=vdyxszrn0qcxymlk#flow-post-vdyxszrn0qcxymlk)

### Examples

- [GoogleMaps](https://sandbox.semantic-mediawiki.org/w/index.php?title=Google_Maps_marker_clustering&mobileaction=toggle_view_mobile)
- [Leaflet](https://sandbox.semantic-mediawiki.org/w/index.php?title=Leaflet_centre&mobileaction=toggle_view_mobile)

**Comment by JeroenDeDauw** [comment] 2020-01-03 12:37
@jdlrobson Thanks for linking https://www.mediawiki.org/wiki/ResourceLoader/Writing_a_MobileFrontend_friendly_ResourceLoader_module. That doc seems a bit out of date though (no extension.json).

Do I really need to add the same 4 lines to _every_ module as done in places like https://github.com/wikimedia/mediawiki-extensions-CentralNotice/blob/master/extension.json? Or is there a way to say all my modules should be loaded on mobile?

**Comment by jdlrobson** [comment] 2020-01-03 17:18
The adding of targets is intentionally cumbersome as it's meant to encourage inspection of the code.

I imagine maps javascript is quite large and given the payload on mobile is quite low it will not just be a case of enabling these modules but altering how they load.

The wiki page looks mostly up to date to me but thanks for pointing out the RL inconsistency I've put that on my todo list.

https://phabricator.wikimedia.org/T235712 also has some additional information that may be useful.

Note significant increases in JS on production wikis can deploy block so I do encourage you to think about that initial payload.

Let me know if you need any other pointers.

**Comment by JeroenDeDauw** [comment] 2020-01-03 17:48
@jdlrobson if someone puts wikitext to embed a map on the page, then this extension needs to load all the JS needed for that map. There are no optional bits. At least none that I can see. Perhaps I'm too close to the "problem" here. Do you have any suggestions or ideas of how to improve the mobile experience?

**Comment by JeroenDeDauw** [comment] 2020-01-03 17:54
> The adding of targets is intentionally cumbersome as it's meant to encourage inspection of the code.

I'm not very concerned about _adding_ these targets. That is a one time thing that takes less time than us discussing it. I'm more concerned with the added noise. Especially in extension.json where I can not loop over the modules and add the targets to all. If that is the way it is, so be it, not a huge deal either way.

**Comment by JeroenDeDauw** [comment] 2020-01-03 17:56
Another note: I actually removed these targets some months ago because I figured they where superfluous. I looked at some resource loader docs to confirm/deny that but was unable to find info on the default.

**Comment by JeroenDeDauw** [comment] 2020-01-03 18:15
@jdlrobson is there a way to define "optional" dependencies between resource loader modules? For instance the marker clustering JS only needs to be loaded in some cases (based on what wikitext is used). This clustering JS is used in some map initialization code. If I define the init code to be dependent on the cluster code, then the cluster code is always loaded. If I don't define this dependency there is a race condition. I know `mw.loader.using` could be used on the JS side to mitigate this but that seem like a hack. Did not find anything in the docs about this either.

**Comment by jdlrobson** [comment] 2020-01-03 19:53
You can set targets on all those modules. Just don't blindly add them to the page for anonymous users with addModuleStyles and addModules.

I think all that's needed here is a frontend or server side check that the map is loaded.

Is the main bulk of the map code loaded when the user interacts with it?

I would expect mobile friendly map embed code to loads a static image and small amount of wire up Javascript by default. when clicked additional code and leaflet.js should be loaded.

**Comment by JeroenDeDauw** [comment] 2020-01-03 22:06
> Is the main bulk of the map code loaded when the user interacts with it?

There is no split between the JS needed to display the map and to interact with it. (The used libraries do not provide such a split.)

Static image plus minimal bootstrap would indeed be nice for mobile.

**Comment by JeroenDeDauw** [comment] 2020-01-03 22:06
Should be fixed with https://github.com/JeroenDeDauw/Maps/commit/97bd7c998fe502d69bcfd56be38ca28fd479d9fd

**Closed by JeroenDeDauw** 2020-01-03 22:06 UTC
Labels: enhancement

**Comment by jdlrobson** [comment] 2020-01-03 22:31
I think you've misunderstood me. I was suggested you provide the code that enable the interactivity on click. 

I am travelling so cannot check this until next week but just updating extension.json and no other files makes me nervous without knowing the following:

* How many bytes of javascript/css does your patch introduce on page load on mobile?
* Is this limited to pages with maps?
* Have you tested on a real mobile device?

**Comment by JeroenDeDauw** [comment] 2020-01-03 23:25
I'm saying the code that provides interactivity is not split from the code that does display. It's all in leaflet.js and related plugins.

I get that it would be better to somehow create a static image though that is not something Leaflet provides out of the box. So this goes into the "nice to have but super costly enhancements" category. You're more than welcome to contribute.

As to how much this changes mobile page load: it restores the behavior that was there for years until I unknowingly broke it some months ago. No one ever complained about it.

> Is this code limited to pages with maps?

Well you don't seem to have a lot of confidence in me I have to say ;)

**Comment by JeroenDeDauw** [comment] 2020-01-03 23:27
What did add a few bytes to every page with a map is https://github.com/JeroenDeDauw/Maps/commit/7903c98309208fce75ffa2c66c4ce1779f575e53. Alternative is using `mw.loader.using` which might well be worse for performance. Being able to specify optional dependencies in resource loader would really be nicer.

**Comment by jdlrobson** [comment] 2020-01-04 04:00
Sorry for the brevity of my messages I only have access to my phone right now. I'll give this bug and fix a proper look next week when back from my travels.

> Well you don't seem to have a lot of confidence in me I have to say ;)

Nothing personal and Im sorry to give this impression. My questions came from not understanding the code that well and not being able to easily look it up.

I'm definitely a little sensitive about any code being added to the mobile site via updating targets as historically there have been performance regressions (and train blockers) for mobile users. Having used leaflet.js myself on my own side projects I know it to be a huge library with a big performance cost and I have seen its mobile compatibility and usablity issues. (e.g. interfering with  scrolling).

I'm sure you've been diligent here and tested the integration with MobileFrontend and its quirks (e.g different parser output) and leaflet.js (e.g. device testing) but I'd like us to document performance impact on first paint, time for first click and associated increase in css and js so I can I give the wikimedia team a heads up if any changes are expected there in what's already a big deployment week.

I will give that my full attention, take a look at the code and provide any follow up advice (if needed) when I have my laptop next week. Thanks for your understanding and patience.

**Comment by JeroenDeDauw** [comment] 2020-01-04 14:03
@jdlrobson As far as I now this extension is not used by Wikimedia.

**Comment by jdlrobson** [comment] 2020-01-04 16:04
Ah okay then that makes this less urgent (i suspect i am getting confused with kartographer?)

Still I'd like to check out the performance side of things as the more good examples in the wild of mobile friendly extensions the better for the ecosystem!

**Comment by JeroenDeDauw** [comment] 2020-01-04 23:49
Kartographer is used by WMF yes.

Map is now working on mobile as seen here: https://sandbox.semantic-mediawiki.org/wiki/Berlin_map?useformat=mobile

Looking at the browser console I suspect there is a lot of non-map related stuff being loaded even though it is not needed on that page.

Focusing just on the Maps extension, loading speed on mobile seems to be fine. The map height might be a problem though. @jdlrobson is there some way to make divs fill the vertical space available in MediaWiki? So that the user can specify they want a "100% high" map, resulting in a wiki page that fills 1 screen?

![image](https://user-images.githubusercontent.com/146040/71772953-e1300380-2f54-11ea-8ed6-4802ab5997f3.png)

**Comment by jdlrobson** [comment] 2020-01-07 00:28
Thanks for the link. I took a closer look at this, 
Before change: (after gzip) 277.94kb of CSS+JS, 15.14kb of this being CSS
After change (after gzip): 348.65kb of JS+CSS,15.4kb of CSS
Without gzipping things are a little more significant but have not considered those.

As you can see the CSS increase is minimal (0.3kb so unlikely to impact anything performance wise). The additional JS marks a 25% increase, but given JS loads asynchronously in mediawiki, the only real concern here is additional bytes. Given the JS is only loaded on pages which have maps this is likely acceptable. I don't have too many performance recommends...

The only recommendation I would make is #599 - this will be better performance wise but more importantly usability wise. Right now the maps are not very useable on a mobile phone. Let me know on that issue if you need any clarifications.

> The map height might be a problem though. If you put it on 600px or so, it might be nice on desktop but is really silly on mobile:
> @jdlrobson is there some way to make divs fill the vertical space available in MediaWiki? So that the user can specify they want a "100% high" map, resulting in a wiki page that fills 1 screen?

If #599 is implemented, you could use position fixed and top/left/bottom/right:0 to cover the entire screen (provided a close icon is available in the top right corner)

I assume when you say fill the vertical space you mean the viewport?
If the map is larger than the viewport it's actually going to be very difficult/possible for the user to scroll the map on a mobile device and understand what's happening.. there will always be a bit of map hidden under the screen. Viewport units would possibly be helpful here - https://css-tricks.com/fun-viewport-units/
You'd probably want to center the map via JS and scope some viewport units in a media query targeting mobile devices when an interaction occurs if you don't go with the overlay suggestion. Hope that helps!

(And again apologies for the rushed mobile replies before. I really should have waited till I was in a better place to respond and give you a quality reply rather than a responsive one!)

**Comment by JeroenDeDauw** [comment] 2020-01-11 02:24
Please don't apologize for volunteering your time. It is much appreciated!

> I assume when you say fill the vertical space you mean the viewport?

Not quite. I was not talking about mobile actually, which likely would need its own solution, perhaps in line with what you suggested.

I'd like to make (some) maps utilize all vertical space available for page content. So rather than having a bunch of "unused space" in the below screenshot, the map would be higher.

![image](https://user-images.githubusercontent.com/146040/72197419-42f2e080-3421-11ea-866a-730ce2b8586e.png)

Like this

![image](https://user-images.githubusercontent.com/146040/72197451-bf85bf00-3421-11ea-97dd-ff91f20b4434.png)

**Comment by jdlrobson** [comment] 2020-01-15 05:10
I see. Not too sure about how you would do this. Maybe try min-height using viewport units and/or display flex. Im sure it's possible and let me know if it works.
