### ISSUE TITLE
Query option link=all is ignored

### ISSUE THREAD

**Issue by m-art-in** [JeroenDeDauw/Maps#415] opened 2018-04-18 15:04 UTC
### Setup

- Maps version: 5.2.0
- MW version: 1.30.0
- PHP version: 7.0.7
- SMW version (if applicable): 2.5.6

### Issue

I generate a simple query in SMW on the special:ask page. There I ask for a property Link (type URL). I set the option link=all to get the direkt URL as link, which works fine on the special:ask page. But as soon as I copy the generated query to an wikipage then the result is without the link. I tried with leaflet and googlemaps

### Steps to reproduce the observation
Link: Ask-Page: 
https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3ARequ%C3%AAter&q=%5B%5Bcategory%3ACustomer%5D%5D&po=%3FHas+coordinates%0D%0A%3FHas+URL%0D%0A&eq=yes&p%5Bformat%5D=leaflet&p%5Bsource%5D=&p%5Blimit%5D=200&p%5Boffset%5D=0&p%5Blink%5D=all&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=%E2%80%A6+weitere+Ergebnisse&p%5Bdefault%5D=&p%5Bwidth%5D=auto&p%5Bheight%5D=350&p%5Bcentre%5D=&p%5Btitle%5D=&p%5Blabel%5D=&p%5Bicon%5D=&p%5Bvisitedicon%5D=&p%5Blines%5D=&p%5Bpolygons%5D=&p%5Bcircles%5D=&p%5Brectangles%5D=&p%5Bwmsoverlay%5D=&p%5Bmaxzoom%5D=&p%5Bminzoom%5D=&p%5Bzoom%5D=&p%5Bdefzoom%5D=14&p%5Blayers%5D%5B%5D=OpenStreetMap&p%5Bscrollwheelzoom%5D=1&p%5Bclustermaxzoom%5D=20&p%5Bclusterzoomonclick%5D=1&p%5Bclustermaxradius%5D=80&p%5Bclusterspiderfy%5D=1&p%5Bstaticlocations%5D=&p%5Bshowtitle%5D=1&p%5Btemplate%5D=&p%5Buserparam%5D=&p%5Bactiveicon%5D=&p%5Bajaxcoordproperty%5D=&p%5Bajaxquery%5D=&sort_num%5B%5D=&order_num%5B%5D=asc&sort_num%5B%5D=&order_num%5B%5D=asc&eq=yes#embed_show
![grafik](https://user-images.githubusercontent.com/15324884/38940462-7929621c-432a-11e8-8b4b-8e9b2b5c6b63.png)

Generated query in my userpage:
https://sandbox.semantic-mediawiki.org/wiki/Utilisateur:Zym
![grafik](https://user-images.githubusercontent.com/15324884/38940480-838611f6-432a-11e8-8d40-1f2b39fcb27f.png)

```
{{#ask:
 [[category:Customer]]
 |?Has coordinates
 |?Has URL
 |format=leaflet
 |limit=200
 |offset=0
 |link=all
 |sort=
 |order=asc
 |headers=show
 |searchlabel=… weitere Ergebnisse
 |width=auto
 |height=350
 |defzoom=14
 |layers=OpenStreetMap
 |scrollwheelzoom=1
 |clustermaxzoom=20
 |clusterzoomonclick=1
 |clustermaxradius=80
 |clusterspiderfy=1
 |showtitle=1
}}
```

**Comment by JeroenDeDauw** [comment] 2018-04-19 01:40
Thanks for reporting this issue!

**Comment by m-art-in** [comment] 2018-10-24 13:40
Is this bug not fixed in Maps 6.* ?

**Comment by JeroenDeDauw** [comment] 2018-10-25 02:15
Probably not. If you upgrade, please let us know, as this is useful info to prioritize work

**Comment by m-art-in** [comment] 2018-11-19 11:39
Sorry for the late reply. I had to set up a testwiki first.
Unfortunately the bug is not fixed.

**System**
MediaWiki : 1.31.1
Semantic MediWiki: 3.0.0
PHP:7.2.5 (apache2handler)
MariaDB: 10.2.15-MariaDB
Maps: 6.0.4

**Comment by m-art-in** [comment] 2018-11-22 09:46
Just made the update to Maps 6.1.0 some behavior as before

**Comment by JeroenDeDauw** [comment] 2018-11-23 01:40
Yeah I have not touched this yet. I've been poking at the code and cleaning it up a bit since it is hard to quickly understand. Still not spotted what the issue is though.

Are the default Leaflet markers showing up for you with 6.1?

**Comment by JeroenDeDauw** [comment] 2018-11-23 02:37
![image](https://user-images.githubusercontent.com/146040/48926753-05f02580-eed1-11e8-930b-20e1d28f4122.png)

Should be fixed now. Together with some related issues. See https://github.com/JeroenDeDauw/Maps/blob/master/RELEASE-NOTES.md

**Closed by JeroenDeDauw** 2018-11-23 02:37 UTC
Labels: Semantic, bug

**Comment by m-art-in** [comment] 2018-11-26 11:40
Thanks for the fix, but

> Are the default Leaflet markers showing up for you with 6.1?
no

**Comment by m-art-in** [comment] 2018-11-26 11:42
The full screen icon [+] on the top left is also gone away

**Comment by JeroenDeDauw** [comment] 2018-11-26 12:07
Uh oh, that is not good! I was hoping it was just on my local wiki...

https://github.com/JeroenDeDauw/Maps/issues/513

**Comment by JeroenDeDauw** [comment] 2018-11-27 01:47
The image issues will be fixed today and a release made as well
